language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
script: coverage run --source=whereismybus230 --omit whereismybus230/test_main.py whereismybus230/test_main.py
after_success:
  - coveralls